export class Parser {
    constructor(options: any, dependencies: any);
    _options: any;
    _hasIHDR: boolean;
    _hasIEND: boolean;
    _emittedHeadersFinished: boolean;
    _palette: any[];
    _colorType: number;
    _chunks: {};
    read: any;
    error: any;
    metadata: any;
    gamma: any;
    transColor: any;
    palette: any;
    parsed: any;
    inflateData: any;
    finished: any;
    simpleTransparency: any;
    headersFinished: any;
    start(): void;
    _parseSignature(data: any): void;
    _parseChunkBegin(data: any): any;
    _crc: CrcCalculator;
    _skipChunk(): void;
    _handleChunkEnd(): void;
    _parseChunkEnd(data: any): void;
    _handleIHDR(length: any): void;
    _parseIHDR(data: any): void;
    _handlePLTE(length: any): void;
    _parsePLTE(data: any): void;
    _handleTRNS(length: any): void;
    _parseTRNS(data: any): void;
    _handleGAMA(length: any): void;
    _parseGAMA(data: any): void;
    _handleIDAT(length: any): void;
    _parseIDAT(length: any, data: any): void;
    _handleIEND(length: any): void;
    _parseIEND(data: any): void;
}
import { CrcCalculator } from "./CrcCalculator.js";
